//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileFoodAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Code_User { get; set; }
        public string Telephone_User { get; set; }
        public int Password_User { get; set; }
    }
}
